offensive_bumper_learning:
  measure: reward
  thresholds: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  min_lesson_length: 1
  signal_smoothing: true
  parameters:
    Paddle_Size: [5, 4.375, 3.75, 3.125, 2.5, 2.5, 2.5]


defensive_bumper_learning:
  measure: reward
  thresholds: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  min_lesson_length: 1
  signal_smoothing: true
  parameters:
         Paddle_Size: [5, 4.375, 3.75, 3.125, 2.5, 2.5, 2.5]