offensive_bumper_learning:
  measure: reward
  thresholds: [0.8, 0.79, 0.78, 0.77, 0.76, 0.75]
  min_lesson_length: 5
  signal_smoothing: true
  parameters:
    speed: [15, 15, 16, 18, 21, 25, 25]
    Paddle_Size: [2, 1.75, 1.5, 1.25, 1, 1, 1]


defensive_bumper_learning:
  measure: reward
  thresholds: [0.8, 0.79, 0.78, 0.77, 0.76, 0.75]
  min_lesson_length: 5
  signal_smoothing: true
  parameters:
         speed: [15, 15, 16, 18, 21, 25, 25]
         Paddle_Size: [2, 1.75, 1.5, 1.25, 1, 1, 1]